### ISSUE TITLE
MacVim errors on :VimuxTogglePane and doesn't :VimuxSendText but finishes without error

### ISSUE THREAD

**Issue by dezza** [preservim/vimux#160]
Have you guys tried using MacVim? I can't use:

`:call VimuxSendText('echo whatever')` it just doesn't appear in the tmux window.

Using `:VimuxRunCommand` works however. But I don't want a split since MacVim is one GUI and have to run tmux besides.

Using `:VimuxTogglePane` it also errors out.

```vim
Error detected while processing function VimuxTogglePane[6].._VimuxTmux:
line    2:
E484: Can't open file /var/folders/_m/2_2m6b0j34n6g3r5qbdv6b480000gn/T/vgmSOPP/56
```

If I'm reading this correctly it should be this line 2 in VimuxTogglePane
https://github.com/benmills/vimux/blob/master/plugin/vimux.vim#L95
But it's probably the next line where it calls _VimuxTmux.

I don't know if this could be a Vim-issue. But I'm happy to take a look at it later.

Console vim (`mvim -v` for MacVim) works with `:VimuxTogglePane` but GUI doesn't.

**Comment by alfunx** [comment]
So you're using MacVim (GUI) and a terminal window running tmux besides? This doesn't seem to be the intended way of using this plugin. What is your goal?

**Comment by dezza** [comment]
`This doesn't seem to be the intended way of using this plugin.`

Thats probably an opinion. I have used it on Linux, WSL and FreeBSD like this without problems - it's probably trivial to get MacVim to work and when I have some days off I will attempt :)

When I execute `:VimuxRunCommand` in a non-tmux vim and have IRC running in tmux it executes the command there due to `:help VimuxConfiguration_use_nearest` `g:VimuxUseNearest` .. Being able to open a tmux and be confident that `:VimuxRunCommand` attempts to run in the closest tmux unless named is a nice feature and for MacVim users and other people using GUI's without tmux this is desirable.

**Comment by alerque** [comment]
Linux/WSL/FreeBSD are all OS platforms, and any way you run tmux in them is expected to work. MacVIM is a GUI that doesn't run in tmux, it is not a TUI. I have no idea what the expected result you are looking for is.

I'd happy to accept any contribution than enabled a workflow for your scenario, but without more details about what you expect there doesn't seem to be anything actionable here. I'm guessing if you want to use a GUI version of VIM rather than a TUI version inside Tmux your problem might be better served with vim splits and terminal commands.

If I'm miss-reading the situation feel free to comment with more detail.
