### ISSUE TITLE
Vimux doesn't accept all tmux pane identifiers

### ISSUE THREAD

**Issue by camgraff** [preservim/vimux#206]
In my config I have logic to dynamically select which pane to run a command in by setting `g:VimuxRunnerIndex` prior to calling `VimuxRunCommand`. However, if I set `g:VimuxRunnerIndex` to `"{down-of}"`, Vimux will not run the command in the correct pane due to [this line](https://github.com/preservim/vimux/blob/master/plugin/vimux.vim#L66) which, as far as I can tell, is supposed to check if the pane exists. The issue is that [`s:hasRunner`](https://github.com/preservim/vimux/blob/master/plugin/vimux.vim#L267) doesn't account for these special pane identifiers.

**Comment by alerque** [comment]
Understood. I would be happy to accept a PR that fixes this bug if you (or anyone else reading this) has any idea how to make it happen.

**Comment by mvanderkamp** [comment]
The issue as I see it is that `g:VimuxRunnerIndex` is really only intended for internal use, as a way of consistently tracking the runner runner pane even if it is moved around. I'm not sure that broadcasting that this variable exists and allowing something like `"{down-of}"` inside it makes sense in that context.

It sounds like what's wanted here is an option to supply the exact `target-pane` search string to use when connecting a runner.

**Comment by mvanderkamp** [comment]
That said, looks like these search strings have been available since tmux 2.2. I think we should not only support them, but use them for the "nearest index" search instead of the current search approach (which doesn't really find the nearest, exactly).

Also, might make sense to rename the internal functions to make it more clear that we are actually looking at the pane/window _id_, not merely its index.
